services:
  - type: web
    name: calm-lovelace
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/queue
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DEFAULT_SAVE_DIR
        value: /data/downloads
      - key: APP_CACHE_DIR
        value: /data/cache
      - key: APP_TEMP_DIR
        value: /data/tmp
      - key: USE_HF_INFERENCE_API
        value: "true"
      - key: HF_TOKEN
        value: ""
